### ISSUE TITLE
[Sugerencia] Crear constructor que reciba por parámetro los argumentos que mandás en los setters.

### ISSUE THREAD

**Issue by jr0me** [florenciaromera/NOAAChallenge#1]
https://github.com/florenciaromera/NOAAChallenge/blob/9d5939cacee7d02e036a11c94d5bb128a2524a3b/src/main/java/ar/com/ada/api/noaa/services/MuestraService.java#L118

Para que los constructores generen objetos completos.

**Comment by floromer** [comment]
no me queda claro, te referís a que le pase los objetos en lugar de los valores?

**Comment by jr0me** [comment]
Claro te debería quedar así:

```java
    private Anomalia createAnomalia(Double alturaNivelMar, Date horarioInicio, Date horarioFin, String tipoAlerta) {
        Anomalia anomalia = new Anomalia(alturaNivelMar, horarioInicio, horarioFin, tipoAlerta);
        return anomalia;
    }
```

**Comment by floromer** [comment]
RESUELTO commit d9f4cd198246a6dac1aa74f0bcbc93dd3b7836c3
