### ISSUE TITLE
Mejorar nombres de tests

### ISSUE THREAD

**Issue by jr0me** [florenciaromera/NOAAChallenge#11]
https://github.com/florenciaromera/NOAAChallenge/blob/290f714de49cdfcf35124a327c11aead33c6142a/src/test/java/ar/com/ada/api/noaa/utilsTests/GeoUtilsTests.java#L15

Los nombres de los tests tienen que ser más descriptivos, es buena práctica que incluyan el escenario que estás testeando y el resultado que se espera, por ejemplo.

_ChequearRangoPlanetarioEsFalsoConLatitudExcedida_

**Comment by floromer** [comment]
commit 4badefb9050fea10b9d6d2790d6c053a48cc4720
