### ISSUE TITLE
Separar en dos tests

### ISSUE THREAD

**Issue by jr0me** [florenciaromera/NOAAChallenge#13]
https://github.com/florenciaromera/NOAAChallenge/blob/290f714de49cdfcf35124a327c11aead33c6142a/src/test/java/ar/com/ada/api/noaa/servicesTests/BoyaServiceTest.java#L23-L28

Es buena práctica tener un único assert por test. Haría dos tests uno chequeando latitud y otro longitud, en el nombre del test incluiría que se está testeando que la coordenada es correcta.

**Comment by floromer** [comment]
commit 4badefb9050fea10b9d6d2790d6c053a48cc4720
