### ISSUE TITLE
Testear bien los casos 

### ISSUE THREAD

**Issue by jr0me** [florenciaromera/NOAAChallenge#14]
https://github.com/florenciaromera/NOAAChallenge/blob/290f714de49cdfcf35124a327c11aead33c6142a/src/test/java/ar/com/ada/api/noaa/servicesTests/BoyaServiceTest.java#L29-L33

Acá deberías chequear por separado que falla cuando ponés una coordenada incorrecta.
Un test debería decir que no se puede crear una boya con latitud incorrecta y el otro con longitud incorrecta.

**Comment by floromer** [comment]
Testeando por separado me explotó, muy buen input y para tener en cuenta a futuro. Ahora estoy corrigiendo. El test de GeoUtils que utiliza el método de chequear (que como me dijiste separé en latitud y longitud) están todos bien. Por lo que el problema está en BoyaServiceTest. Resuelvo y envío

**Comment by jr0me** [comment]
Jaja qué quiere decir que explotó? falló el test? no compila? runtime error?

**Comment by floromer** [comment]
falló el test, expected null but received Optional

**Comment by floromer** [comment]
ahora sí 712a281bcf234a80a88f4fae06da535eef663bdb y 712a281bcf234a80a88f4fae06da535eef663bdb

**Comment by jr0me** [comment]
https://github.com/florenciaromera/NOAAChallenge/commit/712a281bcf234a80a88f4fae06da535eef663bdb#r41921038

**Comment by floromer** [comment]
ahora sí 053fb50e24953ddaaa5c8146b668fdd07b7fb288
![image](https://user-images.githubusercontent.com/55365381/91754611-181bef00-eba0-11ea-8fb6-678bb848c910.png)
