### ISSUE TITLE
Simplificar loop

### ISSUE THREAD

**Issue by jr0me** [florenciaromera/NOAAChallenge#15]
https://github.com/florenciaromera/NOAAChallenge/blob/6b1a887870e21994ffd5cc2b869a196d6ce15269/src/main/java/ar/com/ada/api/noaa/services/MuestraService.java#L94-L123

Estoy pensando que todo esto es innecesariamente complicado porque si o si necesitas que haya más de una muestra para que pueda haber una anomalía.

Una opción para simplificarlo es chequear el tamaño de `muestras`, si es menor que dos, devolvés el `Optional.empty()`.

Si es mayor o igual a 2 seguís con la lógica y tenés que cambiar el tipo de `for` que estás usando por:

```java
for (int i = 0; i < muestras.size() - 1; i++) {
    // re implementar lógica teniendo la muestra anterior como muestras[i] y la muestra actual como muestras[i+1]
}
```

Fijate, antes de re escribir todo igual nota lo que escribiste

```java
            if (mAnterior == null) {
                mAnterior = m;
            } else if (nivelMarMayor500(mAnterior.getAlturaNivelMar(), m.getAlturaNivelMar())) {
                anomalia = new Anomalia(mfinal.getAlturaNivelMar(), mAnterior.getHorarioMuestra(),
                        m.getHorarioMuestra(), ALERTA_IMPACTO);
                break;
            } else {
                mAnterior = m;
            }
```

El cuerpo del primer branch del `if` es igual al del `else` ... lo cual es raro/confuso ...

**Comment by floromer** [comment]
listo commit 0a3d96a8a71d2cbfd2dd6d4efdc812594a647135

**Comment by jr0me** [comment]
Acordate que ahora mismo si encontrás una alerta de impacto después de encontrar una alerta de kaijun solo te devuelve la de impacto porque pisa la anomalía anterior. Esto lo notarías si tuvieses tests con más de una anomalía, los deberías tener... buscá [zombie](https://www.agilealliance.org/resources/sessions/test-driven-development-guided-by-zombies/)

También no te olvides de que estás recorriendo el arraylist de muestras dos veces, si la performance fuese importante tendrías que combinar ambos loops para recorrer la lista una única vez.

Para hacerlo más legible podrías encapsular algunos chequeos y operaciones en funciones auxiliares.
