### ISSUE TITLE
Agregar test para getColor

### ISSUE THREAD

**Issue by jr0me** [florenciaromera/NOAAChallenge#16]
https://github.com/florenciaromera/NOAAChallenge/blob/a774f8cbc1f9f97cf1460a94c578e465946772b1/src/test/java/ar/com/ada/api/noaa/servicesTests/BoyaServiceTest.java#L17

Te falta testear el caso en que get color devuelve VERDE.

**Comment by floromer** [comment]
Listo 0da09d0f7b4805bf33880571c5fbc983a50395d6
