### ISSUE TITLE
Usar constructores paramétricos

### ISSUE THREAD

**Issue by jr0me** [florenciaromera/NOAAChallenge#17]
En estos lugares...

https://github.com/florenciaromera/NOAAChallenge/blob/a774f8cbc1f9f97cf1460a94c578e465946772b1/src/test/java/ar/com/ada/api/noaa/servicesTests/MuestraServiceTest.java#L34-L41

https://github.com/florenciaromera/NOAAChallenge/blob/a774f8cbc1f9f97cf1460a94c578e465946772b1/src/test/java/ar/com/ada/api/noaa/servicesTests/MuestraServiceTest.java#L57-L64

https://github.com/florenciaromera/NOAAChallenge/blob/a774f8cbc1f9f97cf1460a94c578e465946772b1/src/test/java/ar/com/ada/api/noaa/servicesTests/MuestraServiceTest.java#L83-L90

Fijate si tenés el mismo problema en algún otro lado

**Comment by floromer** [comment]
Me parece que solamente el problema me quedó ahí porque como es ambiente de test no sé si se deben generar constructores en las entidades que sean solo utilizados en ese ámbito. Pero podría hacer una constructor en la entidad Muestra que sea un public MuestraTest() y que reciba por parámetro solo lo que le seteo para tal fin. Vos qué decís?

**Comment by jr0me** [comment]
~~No entiendo lo que decís... los constructores de Muestra ya los tenés:~~

https://github.com/florenciaromera/NOAAChallenge/blob/a774f8cbc1f9f97cf1460a94c578e465946772b1/src/main/java/ar/com/ada/api/noaa/entities/Muestra.java#L29-L36

~~Veo que no están todos los parámetros tal vez tengas que tener un segundo constructor...~~

**Comment by jr0me** [comment]
Ok, ya entendí...

El problema es que justamente cómo el constructor por defecto es público, podés crear objetos que no tengan boya ni embarcación que es lo que estás haciendo en el test.

**Comment by jr0me** [comment]
Pero por lo que venimos hablando eso nunca debería pasar, nunca tengas objetos incompletos e inválidos, ni siquiera en los tests.

Construí instancias de Muestras usando el constructor que hiciste, si te falta una boya y una embarcación, crealas también.

**Comment by jr0me** [comment]
Ya que estamos fijate si el constructor por defecto de la muestra lo podés marcar como privado -y si podés, hacelo para todas las clases que puedas-.

**Comment by floromer** [comment]
Hice un constructor que recibe solo lo que necesito para el ambiente de test y corregí lo de las listas, está probado, corren bien. Ahora chequeo lo del constructor
commit 55f0321a7839767612f9708fc2f78a56cee3fb21

**Comment by floromer** [comment]
jajaja, ok, le seteo todo para usar el constructor que ya tengo

**Comment by jr0me** [comment]
Modificar código para los tests, o agregar, no está bueno, eso incluye crear constructores especiales para los tests.

Tal vez haya un caso donde no tengas alternativa, pero en este escenario es totalmente evitable.

**Comment by floromer** [comment]
https://github.com/florenciaromera/NOAAChallenge/issues/17#issuecomment-685101206 leí éste dps de que había hecho las correcciones porque cuando arranqué el último comentario era el anterior a éste que te hago referencia. Ahora corrijo, entiendo lo que me decís, justamente por eso no había hecho lo del constructor. Tengo que mockear el service de boya xq también tengo que pasarle una boya. Corrijo y vuelvo a pushear

**Comment by floromer** [comment]
commit 783935a5f9df31827eced10c24b3375ca5afc316
