### ISSUE TITLE
Inicializar variables

### ISSUE THREAD

**Issue by jr0me** [florenciaromera/NOAAChallenge#18]
https://github.com/florenciaromera/NOAAChallenge/blob/a774f8cbc1f9f97cf1460a94c578e465946772b1/src/test/java/ar/com/ada/api/noaa/servicesTests/MuestraServiceTest.java#L66-L67

Mové el array de la línea 56 a la línea 65 ... es buena práctica postergar introducir variables hasta último momento, en la línea que la declarás y que finalmente la usás pasan demasiadas cosas.

Probá también declarar e inicializar la variable en una misma línea, fijate si esto funciona:

```java
List<Muestra> muestras = new ArrayList<>(List.of(m1, m2));
```

Buscá este tipo de patrones y modificalos, vi más en este mismo archivo

**Comment by floromer** [comment]
commit 783935a5f9df31827eced10c24b3375ca5afc316
