### ISSUE TITLE
Anomalia fixes

### ISSUE THREAD

**Issue by jr0me** [florenciaromera/NOAAChallenge#19]
https://github.com/florenciaromera/NOAAChallenge/blob/55f0321a7839767612f9708fc2f78a56cee3fb21/src/main/java/ar/com/ada/api/noaa/anomalias/Anomalia.java#L6-L9

Una vez que las seteas nunca las modificás, así que marcalas como `final`.

Por otro lado, una vez que las marcás como `final` no tiene sentido tener ningún seter, así que borralos.

Marcá el default constructor como `private`

https://github.com/florenciaromera/NOAAChallenge/blob/55f0321a7839767612f9708fc2f78a56cee3fb21/src/main/java/ar/com/ada/api/noaa/anomalias/Anomalia.java#L11-L12

En vez de crear issues para todas las demás clases que tenés, te diría que intenes aplicar esto en cada lugar que puedas: primero fijate si los seters que estás usando pueden eliminarse usando un constructor paramétrico, después si se puede marcá todo como final, constructores por defecto como privados, y eliminá geters y seters que no uses.

El código que se escribe tiene que ser testeado y es potencial fuente de bugs, así que eliminar código siempre es un poco satisfactorio. :)

**Comment by floromer** [comment]
Listo fe1ebb422f983d441547d85805524908b506dd7a
No dejé el constructor por default (ni público ni private) porque me marcaba error y ésto era lo que tiaraba: 
The constructor Anomalia() is never used locallyJava(603979910)
The blank final field alturaMarActual may not have been initializedJava(33554513)
The blank final field horarioFin may not have been initializedJava(33554513)
The blank final field horarioInicio may not have been initializedJava(33554513)
The blank final field tipoAlerta may not have been initializedJava(33554513)

**Comment by jr0me** [comment]
Ok, fijate si compila y corren los tests. Por lo que escuché Hibernate requería que hubiese constructores por default. Aunque si esta clase no la estás persistiendo tal vez no hace falta. Tendrás que investigar, yo no sé nada del framework realmente.
