### ISSUE TITLE
Mergear líneas

### ISSUE THREAD

**Issue by jr0me** [florenciaromera/NOAAChallenge#2]
https://github.com/florenciaromera/NOAAChallenge/blob/9d5939cacee7d02e036a11c94d5bb128a2524a3b/src/main/java/ar/com/ada/api/noaa/controllers/BoyaController.java#L21

y

https://github.com/florenciaromera/NOAAChallenge/blob/9d5939cacee7d02e036a11c94d5bb128a2524a3b/src/main/java/ar/com/ada/api/noaa/controllers/BoyaController.java#L22

Puede escribirse en una sola línea

**Comment by floromer** [comment]
ya lo tenía mergeado pero no estaba pusheado por lo que vi
