### ISSUE TITLE
Tests set up

### ISSUE THREAD

**Issue by jr0me** [florenciaromera/NOAAChallenge#20]
https://medium.com/@rhamedy/junit-annotations-every-developer-should-know-eb972a7a26c9

Si ves bien en los tests que escribiste siempre repetis las mismas acciones. Creas una muestra, la agregás a una lista, etc...

Para no repetir código en los frameworks de testing está el concepto de SetUp, es un bloque de código que se ejecuta antes de todos los tests, yo crearía en ese lugar las muestras que necesites con nombres que describan bien lo que son, por ejemplo muestraConLatitudInvalida, muestraConLongitudInvalida, muestraValida, muestraValidaConAltura200, etc... 

Las objetos que necesites en los tests los declaras como variables en la clase  `public class MuestraServiceTest` y las inicializás en la función de set up.

Según el link que te pasé la función de setUp tiene que llevar el annotation `@BeforeAll` y para eso tenes que importar algo de JUnit.

```java
import org.junit.jupiter.api.BeforeAll
import org.junit.jupiter.api.AfterAll
```

Probalo, vas a tener que ingeniartelas... también podés hacer una función para que posterior a cada test te vacie la lista de muestras que estás usando, ya que por lo que vi las muestras que agregas difieren un poco según el test.

**Comment by floromer** [comment]
Genial! gracias por el link, ahora lo veo. Estoy haciendo refactor de otro repo siguiendo tus consejos en éste

**Comment by floromer** [comment]
commit 783935a5f9df31827eced10c24b3375ca5afc316

**Comment by jr0me** [comment]
En general creo que es mejor tener un poco de repetición antes que tests que dependan del orden en que se ejecuten, pero bueno así está bien!
