### ISSUE TITLE
Crear constructor que reciba una Anomalia en vez de todos sus miembros como argumentos

### ISSUE THREAD

**Issue by jr0me** [florenciaromera/NOAAChallenge#3]
https://github.com/florenciaromera/NOAAChallenge/blob/9d5939cacee7d02e036a11c94d5bb128a2524a3b/src/main/java/ar/com/ada/api/noaa/controllers/MuestraController.java#L69

**Comment by floromer** [comment]
Resuelto, commit n° fe14147fa3d5c5058596e7342fc4a2b82cff8261

**Comment by jr0me** [comment]
Mira el comentario del commit
