### ISSUE TITLE
Crear constructor de Boya que reciba argumentos para borrar setters

### ISSUE THREAD

**Issue by jr0me** [florenciaromera/NOAAChallenge#4]
https://github.com/florenciaromera/NOAAChallenge/blob/9d5939cacee7d02e036a11c94d5bb128a2524a3b/src/main/java/ar/com/ada/api/noaa/services/BoyaService.java#L20

**Comment by floromer** [comment]
RESUELTO commit d630fab153b31cc25894b3dc9a4ebb2165ad15ef
