### ISSUE TITLE
Muestra tiene que tener un constructor para recibir estos argumentos y no usar los setters en la construcción de los objetos

### ISSUE THREAD

**Issue by jr0me** [florenciaromera/NOAAChallenge#5]
https://github.com/florenciaromera/NOAAChallenge/blob/9d5939cacee7d02e036a11c94d5bb128a2524a3b/src/main/java/ar/com/ada/api/noaa/services/MuestraService.java#L27

**Comment by floromer** [comment]
RESUELTO commit 65acd82c36d01fc5fac67f3449aaea3364070922
