### ISSUE TITLE
No hace falta el if ... else ...

### ISSUE THREAD

**Issue by jr0me** [florenciaromera/NOAAChallenge#6]
https://github.com/florenciaromera/NOAAChallenge/blob/9d5939cacee7d02e036a11c94d5bb128a2524a3b/src/main/java/ar/com/ada/api/noaa/utils/GeoUtils.java#L6

podés poner directamente:

```java
return !(Math.abs(latitud) > 90 && Math.abs(longitud) > 180);
```

O lo que es lo mismo:

```java
return Math.abs(latitud) <= 90 || Math.abs(longitud) <= 180;
```

**Comment by floromer** [comment]
RESUELTO commit 82cba65916d69d276ab73ed1e9f2f350f56e4487
éste lo tenía resuelto de ayer pero no lo había pusheado, usé un if in line

**Comment by jr0me** [comment]
Pero lo dejaste feo... 

Si vas a devolver un booleano que es el resultado de una comparación, entonces directamente devolvé la comparación como te puse ahí

```java
return Math.abs(latitud) <= 90 || Math.abs(longitud) <= 180;
```

**Comment by floromer** [comment]
commit 00715de02fbf310accd16de34e28d7a98e5d21c2 ahora quedó lindo! jajaja
