### ISSUE TITLE
Ya no necesitás esta función

### ISSUE THREAD

**Issue by jr0me** [florenciaromera/NOAAChallenge#7]
https://github.com/florenciaromera/NOAAChallenge/blob/d9f4cd198246a6dac1aa74f0bcbc93dd3b7836c3/src/main/java/ar/com/ada/api/noaa/services/MuestraService.java#L126

Tenés el constructor... está función no hace falta... borrala y utilizá el constructor de Anomalía en cambio.

**Comment by floromer** [comment]
RESUELTO commit 290f714de49cdfcf35124a327c11aead33c6142a
