### ISSUE TITLE
Corregir chequeo

### ISSUE THREAD

**Issue by jr0me** [florenciaromera/NOAAChallenge#8]
https://github.com/florenciaromera/NOAAChallenge/blob/290f714de49cdfcf35124a327c11aead33c6142a/src/main/java/ar/com/ada/api/noaa/services/BoyaService.java#L40-L43

En varios lados estás verificando si un valor absoluto es menor que un número negativo (-100, -50) eso es siempre falso.
En otros lugares chequeas si es mayor que un número negativo, lo cual es siempre verdadero.
Por definición el valor absoluto de cualquier número es un número mayor o igual a 0, o sea, no negativo.

**Comment by floromer** [comment]
sabés que justo lo vi y corregí, ahora pusheo

**Comment by floromer** [comment]
commit 4c3b9952abcb67cd4aabc2444a7ba74b45345a40 ahí dejo, prefiero que empieces vos a cerrar los comentarios si ves que lo resolví bien

**Comment by jr0me** [comment]
Te dejé unos comentarios en el commit 4c3b995

**Comment by floromer** [comment]
RESUELTO commit a94df7939cc5606a3daeb349ee8a3c728d461c7a

**Comment by jr0me** [comment]
Casi! pero no a94df79

**Comment by floromer** [comment]
me parece que esta vez sí, perdón el ida y vuelta 5e8705465019d805cc776a29855b8947057ca9f4

**Comment by jr0me** [comment]
No problem... Está bien... cuando puedas sacá el Math.abs del 100 y del 50... que es innecesario.

```java
        if (Math.abs(alturaNivelMar) >= 100) {
            color = ROJO;
        } else if (Math.abs(alturaNivelMar) >= 50) {
            color = AMARILLO;
        }
```
