### ISSUE TITLE
Posible duplicación de info

### ISSUE THREAD

**Issue by jr0me** [florenciaromera/NOAAChallenge#9]
https://github.com/florenciaromera/NOAAChallenge/blob/290f714de49cdfcf35124a327c11aead33c6142a/src/main/java/ar/com/ada/api/noaa/entities/Muestra.java#L18-L24

Esto es para verificar, tal vez no está mal, veo que la Muestra se construye con una boya, y al mismo tiempo tiene una latitud y una longitud.

Si la boya no se va a mover nunca, tal vez no hace falta guardar en la muestra la latitud y la longitud,, ya que la podrías obtener a través de la boya...

Pero si la boya puede ser eliminada, o se puede modificar sus valores de latitud y longitud, entonces está bien guardarlos.

**Comment by floromer** [comment]
sabés que eso fue un tema del challenge que no lo hablamos. Yo pensé lo mismo cuando lo vi pero especificaba los atributos de Boya y Muestra y estaban en ambas entidades. Boya tiene altituInstalacion y longitudInstalacion, no sé si deja estos atributos tb en muestra por si varían estos datos cuando se registra una nueva muestra. Averiguo y dps confirmo

**Comment by jr0me** [comment]
Entonces dejalo así!
No es ilógico que la boya se pueda mover, de hecho, si está en el mar se mueve todo el tiempo...
